Traceback (most recent call last):
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "E:\programas\Anaconda\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from dimod import BinaryQuadraticModel, to_networkx_graph
# definimos los valores de la matriz del BQM
bqm = BinaryQuadraticModel('SPIN')
bqm.add_variable(0, -1)
bqm.add_variable(1, -1)
bqm.add_variable(4, -1)
bqm.add_variable(5, -1)
# bqm.add_variable(6,-1) # lo aÃ±adÃ­ yo de prueba
bqm.add_interaction(0, 4, 1.0)
bqm.add_interaction(0, 5, 1.0)
bqm.add_interaction(1, 4, 1.0)
bqm.add_interaction(1, 5, 1.0)
# bqm.add_interaction(0, 1, 1.0) # lo aÃ±adÃ­ so de prueba


import networkx as nx

nx.draw(to_networkx_graph(bqm))
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[3], line 18[0m
[0;32m     13[0m [38;5;66;03m# bqm.add_interaction(0, 1, 1.0) # lo aÃ±adÃ­ so de prueba[39;00m
[0;32m     16[0m [38;5;28;01mimport[39;00m [38;5;21;01mnetworkx[39;00m [38;5;28;01mas[39;00m [38;5;21;01mnx[39;00m
[1;32m---> 18[0m [43mnx[49m[38;5;241;43m.[39;49m[43mdraw[49m[43m([49m[43mto_networkx_graph[49m[43m([49m[43mbqm[49m[43m)[49m[43m)[49m

File [1;32mc:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\networkx\drawing\nx_pylab.py:105[0m, in [0;36mdraw[1;34m(G, pos, ax, **kwds)[0m
[0;32m     49[0m [38;5;28;01mdef[39;00m [38;5;21mdraw[39m(G, pos[38;5;241m=[39m[38;5;28;01mNone[39;00m, ax[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwds):
[0;32m     50[0m [38;5;250m    [39m[38;5;124;03m"""Draw the graph G with Matplotlib.[39;00m
[0;32m     51[0m 
[0;32m     52[0m [38;5;124;03m    Draw the graph as a simple representation with no node[39;00m
[1;32m   (...)[0m
[0;32m    103[0m [38;5;124;03m    https://networkx.org/documentation/latest/auto_examples/index.html[39;00m
[0;32m    104[0m [38;5;124;03m    """[39;00m
[1;32m--> 105[0m     [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m    107[0m     [38;5;28;01mif[39;00m ax [38;5;129;01mis[39;00m [38;5;28;01mNone[39;00m:
[0;32m    108[0m         cf [38;5;241m=[39m plt[38;5;241m.[39mgcf()

[1;31mModuleNotFoundError[0m: No module named 'matplotlib'

