Traceback (most recent call last):
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "E:\programas\Anaconda\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
visualize_results(G, group_1, group_2, sep_group, illegal_edges)
------------------

----- stdout -----

Visualizing output...
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mUnboundLocalError[0m                         Traceback (most recent call last)
Cell [1;32mIn[16], line 1[0m
[1;32m----> 1[0m [43mvisualize_results[49m[43m([49m[43mG[49m[43m,[49m[43m [49m[43mgroup_1[49m[43m,[49m[43m [49m[43mgroup_2[49m[43m,[49m[43m [49m[43msep_group[49m[43m,[49m[43m [49m[43millegal_edges[49m[43m)[49m

Cell [1;32mIn[15], line 29[0m, in [0;36mvisualize_results[1;34m(G, group_1, group_2, sep_group, illegal_edges, guardar)[0m
[0;32m     26[0m     output_name [38;5;241m=[39m [38;5;124m'[39m[38;5;124mseparator.png[39m[38;5;124m'[39m
[0;32m     27[0m     plt[38;5;241m.[39msavefig(output_name)
[1;32m---> 29[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;130;01m\t[39;00m[38;5;124mOutput stored in[39m[38;5;124m"[39m, [43moutput_name[49m)

[1;31mUnboundLocalError[0m: local variable 'output_name' referenced before assignment

