Traceback (most recent call last):
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\jupyter_core\utils\__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "E:\programas\Anaconda\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "c:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
4.5*bin_used[0]*bin_used[1]*bin_used[3]
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[9], line 1[0m
[1;32m----> 1[0m [38;5;241;43m4.5[39;49m[38;5;241;43m*[39;49m[43mbin_used[49m[43m[[49m[38;5;241;43m0[39;49m[43m][49m[38;5;241;43m*[39;49m[43mbin_used[49m[43m[[49m[38;5;241;43m1[39;49m[43m][49m[38;5;241;43m*[39;49m[43mbin_used[49m[43m[[49m[38;5;241;43m3[39;49m[43m][49m

File [1;32mc:\users\francisco\desktop\dwaveocean\ocean\lib\site-packages\dimod\binary\binary_quadratic_model.py:345[0m, in [0;36mBinaryQuadraticModel.__mul__[1;34m(self, other)[0m
[0;32m    343[0m [38;5;28;01mif[39;00m [38;5;28misinstance[39m(other, BinaryQuadraticModel):
[0;32m    344[0m     [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m ([38;5;28mself[39m[38;5;241m.[39mis_linear() [38;5;129;01mand[39;00m other[38;5;241m.[39mis_linear()):
[1;32m--> 345[0m         [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m(
[0;32m    346[0m             [38;5;124m"[39m[38;5;124mcannot multiply BQMs with interactions[39m[38;5;124m"[39m)
[0;32m    347[0m     [38;5;28;01melif[39;00m other[38;5;241m.[39mnum_variables [38;5;129;01mand[39;00m other[38;5;241m.[39mvartype [38;5;241m!=[39m [38;5;28mself[39m[38;5;241m.[39mvartype:
[0;32m    348[0m         [38;5;66;03m# promote self[39;00m
[0;32m    349[0m         [38;5;28;01mreturn[39;00m QuadraticModel[38;5;241m.[39mfrom_bqm([38;5;28mself[39m) [38;5;241m*[39m other

[1;31mTypeError[0m: cannot multiply BQMs with interactions

